SCANS_COLLECTION: str='scans'
CORS_COLLECTION: str='cors'
PORTS_COLLECTION: str='ports'
DNS_COLLECTION:str='dns'
SECURITY_HEADERS_COLLECTION:str='securityHeaders'
SSL_COLLECTION: str='ssl'
SUBDOMAINS_COLLECTION:str='subdomains'


